In [1]:
import numpy as np

#checking for missing values


In [6]:
data_numeric=np.loadtxt("datasets/lending-company-numeric.csv",delimiter=(','))
data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [9]:
np.isnan(data_numeric)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       ...,
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [10]:
np.isnan(data_numeric).sum()

0

In [29]:
lending_co_data_numeric_NAN=np.genfromtxt("datasets/lending-company-numeric-nan.csv",delimiter=(','))
lending_co_data_numeric_NAN

array([nan, nan, nan, ..., nan, nan, nan])

In [30]:
np.isnan(lending_co_data_numeric_NAN)

array([ True,  True,  True, ...,  True,  True,  True])

In [31]:
np.isnan(lending_co_data_numeric_NAN).sum()

1043

### Dealing with the Missing Data, by Zero Filling

In [38]:
lending_co_data_numeric_NAN=np.genfromtxt("datasets/lending-company-numeric-nan.csv",delimiter=(','),filling_values=0)
lending_co_data_numeric_NAN

array([0., 0., 0., ..., 0., 0., 0.])

In [39]:
np.isnan(lending_co_data_numeric_NAN)

array([False, False, False, ..., False, False, False])

In [40]:
np.isnan(lending_co_data_numeric_NAN).sum()

0

In [41]:
lending_co_data_numeric_NAN

array([0., 0., 0., ..., 0., 0., 0.])

### Substituting Missing Values with Mean/Max values

In [43]:
lending_co_data_numeric_NAN=np.genfromtxt("datasets/lending-company-numeric-nan.csv",delimiter=(';'))
lending_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [48]:
temporary_fill=np.nanmax(lending_co_data_numeric_NAN)

temporary_fill

64002.0

In [53]:
lending_co_data_numeric_NAN=np.genfromtxt("datasets/lending-company-numeric-nan.csv",delimiter=(';'),filling_values=temporary_fill)
lending_co_data_numeric_NAN

array([[2.0000e+03, 4.0000e+01, 3.6500e+02, 3.1210e+03, 4.2410e+03,
        1.3621e+04],
       [2.0000e+03, 4.0000e+01, 3.6500e+02, 3.0610e+03, 4.1710e+03,
        1.5041e+04],
       [1.0000e+03, 4.0000e+01, 3.6500e+02, 2.1600e+03, 3.2800e+03,
        1.5340e+04],
       ...,
       [6.4002e+04, 4.0000e+01, 3.6500e+02, 4.2010e+03, 5.0010e+03,
        1.6600e+04],
       [1.0000e+03, 4.0000e+01, 3.6500e+02, 2.0800e+03, 3.3200e+03,
        1.5600e+04],
       [2.0000e+03, 4.0000e+01, 3.6500e+02, 4.6010e+03, 4.6010e+03,
        1.6600e+04]])

In [54]:
np.isnan(lending_co_data_numeric_NAN)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       ...,
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [55]:
np.isnan(lending_co_data_numeric_NAN).sum()

0

In [56]:
lending_co_data_numeric_NAN=np.genfromtxt("datasets/lending-company-numeric-nan.csv",delimiter=(';'))
lending_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [58]:
temporary_mean=np.nanmean(lending_co_data_numeric_NAN)

In [59]:
temporary_mean

4758.213571190397

In [64]:
temporary_mean=np.nanmean(lending_co_data_numeric_NAN,axis=0).round(2)
temporary_mean

array([ 2250.25,    46.11,   365.  ,  3895.99,  5160.75, 16571.44])

In [65]:
temporary_mean[0]

2250.25

In [66]:
temporary_mean[1]

46.11